{% set name = "plate-model-manager" %}
{% set version = "1.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: d8ee7a308917d438ede3bea327e5256f96446d232b4766c33ff09381665ca025

build:
  entry_points:
    - pmm = plate_model_manager.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0.0
    - wheel
    - pip
    - setuptools-git-versioning
  run:
    - python >={{ python_min }}
    - aiohttp
    - requests
    - nest-asyncio

test:
  imports:
    - plate_model_manager
  commands:
    - pip check
    - pmm --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/michaelchin/plate-model-manager
  summary: Plate Model Manager
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE

extra:
  recipe-maintainers:
    - michaelchin
