{% set name = "plate-model-manager" %}
{% set version = "1.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/plate-model-manager-{{ version }}.tar.gz
  sha256: b01c418675ba258ab2672e2eb392ed7f2adf5de640017353e7fc33211f7eaf53

build:
  entry_points:
    - pmm = plate_model_manager.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=61.0.0
    - wheel
    - pip
  run:
    - python >=3.9
    - aiohttp
    - requests

test:
  imports:
    - plate_model_manager
  commands:
    - pip check
    - pmm --help
  requires:
    - pip

about:
  home: https://github.com/michaelchin/plate-model-manager
  summary: Plate Model Manager
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE

extra:
  recipe-maintainers:
    - michaelchin
